### ISSUE TITLE
Distribution: build wheels and include MDAL binary

### ISSUE THREAD

**Issue by caspervdw** [ViRGIS-Team/mdal-python#9]
For our release pipelines, we prefer to use binary wheels, because that prevents lengthy compilation steps.

mdal-python however doesn't have "manylinux" builds so we have to resort to building mdal and mdal-python ourselves.

@runette Are you open for a build pipeline implementation using cibuildwheel? I have experience with these (for instance in [shapely](https://github.com/shapely/shapely/blob/main/.github/workflows/release.yml) This would include injecting the MDAL binary into the wheel, which is a customary thing to do.

**Comment by runette** [comment]
As long as you are capable to set it all up and it is done through a CI process - I am good. I exclusively use Conda so that  has been the main focus until now.

The problem is always that MDAL has a dependency on GDAL and that brings a lot of complication for binary distributions. I am not sure how that would be addressed

**Comment by caspervdw** [comment]
The GDAL dependency indeed significantly complicates matters. Injecting the full library (as is customary) breaks down if there are other GDAL usages from the same Python environment (like Fiona, rasterio, or the direct swig bindings)

In that case we are in the same spot as Fiona, which does include GDAL in the binary wheel dist, but clearly states that isn’t for production use. https://fiona.readthedocs.io/en/stable/install.html#easy-installation

An additional complication with mdal is that it isn’t available through the default apt repo (like gdal).

It would significantly help if the source distribution of mdal-python would include the mdal source, so that it might be compiled in one step against the system gdal (which is easily attained) . A bit like the gdal swig bindings.

Then (as a second step) the binary dist could include gdal and mdal binaries.

What do you think ?

**Comment by runette** [comment]
I think it would be very good to have it compile MDAL based on the system GDAL.

Including the GDAL (and dependencies) binaries would be very difficult since there tend to be too many versions in circulation - QGIS always seems to be using different versions of GDAL in the same version of QGIS depending if you are on Windows or Mac - for instance.

**Comment by caspervdw** [comment]
It's indeed a "can of worms" to include GDAL binaries, in combination with `Fiona` or `rasterio`.

My colleague @elisallenens spent some time on this issue and he came to the conclusion that it would be easiest for MDAL to be distributed as a deb package (for a selection of versions). See https://github.com/lutraconsulting/MDAL/issues/465 . Installation then would be: 1) add custom apt repository 2) apt install mdal-dev 3) pip install mdal-python

The other option (that I described earlier) to have python-mdal compile mdal for you, if you think about it, requires merging the two repositories into. This is because the MDAL code needs to be distributed with python-mdal and because they need to have the same release cadence. It would also be easier for them to have the same licenses. This requires some coordination but to be it feels like the best option in the long run. Tagging @PeterPetrik from Lutra consulting.
